# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rusty_symbol", path: "/Users/akifumitomiyama/work/private/rusty_symbol"
gem "pry"
